server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - name: LoggingFilter
      routes:
        - id: movieRoute
          uri: http://movie-service-final:8082/
          predicates:
            - Path=/movies/**
        - id: catalogRoute
          uri: http://catalog-service-final:8082/
          predicates:
            - Path=/catalogs/**
        - id: serieRoute
          uri: http://serie-service-final:8086/
          predicates:
            - Path=/series/**

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: API Gateway Final Nadia Martin Montesi
