server:
  port: 8080

spring:
  eureka:
    client:
      service-url:
        defaultZone: http://eureka-service-final:8761/eureka/
  cloud:
    gateway:
      routes:
        - id: movieRoute
          uri: http://localhost:8082/
          predicates:
            - Path=/movies/**
        - id: catalogRoute
          uri: http://localhost:8084/
          predicates:
            - Path=/catalogs/**
        - id: serieRoute
          uri: http://localhost:8086/
          predicates:
            - Path=/series/**

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: API Gateway Final Nadia Martin Montesi
