server:
  port: 8086

spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: finalBackSerie
      port: 27018
      host: mongodb-serie

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Serie Microservice Final Nadia Martin Montesi
